### ISSUE TITLE
Make Landing Page more Responsive to Mobile

### ISSUE THREAD

**Issue by charmzzyyy** [datagovsg/redeem-landing#68]
**Landing Page**
- [x] Mobile header to be using display 2 font (i.e. font size 40, semi bold)
![image](https://user-images.githubusercontent.com/53885249/145562681-346430ac-87f9-4c2a-ba29-364dab29c7ce.png) 
- [ ] mobile font sizes will be different from desktop (apart from body)
- [x] Reduce margin between government agencies and merchants
![image](https://user-images.githubusercontent.com/53885249/145562970-ec6a64ca-f84c-4770-83ae-05adc3c9d557.png)
- [ ] Padding left and right should be 24px each instead of 15px
- [x] Increase space between each RedeemSG impact (actual implemented vs figma mock)
![image](https://user-images.githubusercontent.com/53885249/145598604-296f869d-8800-4521-b1b8-f15d5c9f4538.png)

**Comment by limli** [comment]
#77 should fix the issues that are checked above.

> Padding left and right should be 24px each instead of 15px

bootstrap's default padding is 15px, might be a bit hard to modify, or take a while to check how to do this properly

> mobile font sizes will be different from desktop (apart from body)

for while one?

**Comment by charmzzyyy** [comment]
> bootstrap's default padding is 15px, might be a bit hard to modify, or take a while to check how to do this properly

Can fix this another time then

> mobile font sizes will be different from desktop (apart from body)

Can go through with you later! https://www.figma.com/file/NVOwL54Ok7lEm9azmLjCRd/Redeem-Design-System?node-id=2153%3A570
