### ISSUE TITLE
Improving organization for team stuff - see what we want to do 4 April

### ISSUE THREAD

**Issue by talithachin** [datagovsg/redeem-landing#94]
To inform team on 4 april 
- [x] Take a vote during team sync on whether we prefer the github board to be organized by p1/2/3 or by repo 
- [x] install a bot to get people to report what they did about 2 hours before team sync 
- [x] Team syncs: organize in terms of (1) anything to discuss for current immediate launches (2) anything to discuss for generic product (3)CBDC/ parking, AOB. 
- [x] everyone to start documenting rfc link in working doc 

Other to do:
- [ ] reorg the working document

**Comment by charmzzyyy** [comment]
@talithachin to update:
- The team prefers the P1-3 organisation for Github board as there are several issues that may span across multiple repos. Sorting according to priorities makes it easier for them to know what to work on next.
- Slack reminder for team updates is scheduled for 11am every Mon and Wed.
